version: "3"

services:
  
  jenkins-master:
    image: meetveracity/jenkins-lib-test
    build:
      context: ./test/jenkins
    ports:
      - "8080:8080"
    environment:
      - ADMIN_PASSWORD=admin

  
  